# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4fd8a56e71a3f82c8a65986839b3357518d1b0a75d794fec570415fb6513c2a6371f38f07befc8f972f12e3206117cb59f42471558cb113d1855e2be9091e13e

test:
  secret_key_base: 9a4ea50dfa6c1edb9f2e1f3ce61663f12c175d7c3fa017d26194a65f44bc9cb0da27b7204c0054d89e88bc92638c70b06d74aa0616bcbf97ae676185914a05eb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
